openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'http://localhost:8080/'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: products
    description: Product Inventory
paths:
  /products:
    get:
      tags:
        - products
      summary: List of products
      operationId: Find Inventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: productName
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
        - in: query
          name: offset
          description: index of the product item
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - id
                    - name
                    - manufacturer
                    - releaseDate
                  properties:
                    id:
                      type: string
                      format: uuid
                      example: d290f1ee-6c54-4b01-90e6-d701748f0851
                    name:
                      type: string
                      example: Widget Adapter
                    releaseDate:
                      type: string
                      format: date-time
                      example: '2016-08-29T09:12:33.001Z'
                    manufacturer:
                      required:
                        - name
                      properties:
                        name:
                          type: string
                          example: ACME Corporation
                        homePage:
                          type: string
                          format: url
                          example: 'https://www.acme-corp.com'
                        phone:
                          type: string
                          example: 408-867-5309
                      type: object
        '400':
          description: bad input parameter
    post:
      tags:
        - products
      summary: adds an inventory item
      operationId: addInventory
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - name
                - manufacturer
                - releaseDate
              properties:
                id:
                  type: string
                  format: uuid
                  example: d290f1ee-6c54-4b01-90e6-d701748f0851
                name:
                  type: string
                  example: Widget Adapter
                releaseDate:
                  type: string
                  format: date-time
                  example: '2016-08-29T09:12:33.001Z'
                manufacturer:
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      example: ACME Corporation
                    homePage:
                      type: string
                      format: url
                      example: 'https://www.acme-corp.com'
                    phone:
                      type: string
                      example: 408-867-5309
                  type: object
        description: Inventory item to add
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - manufacturer
        - releaseDate
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
        releaseDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        manufacturer:
          required:
            - name
          properties:
            name:
              type: string
              example: ACME Corporation
            homePage:
              type: string
              format: url
              example: 'https://www.acme-corp.com'
            phone:
              type: string
              example: 408-867-5309
          type: object
    Manufacturer:
      required:
        - name
      properties:
        name:
          type: string
          example: ACME Corporation
        homePage:
          type: string
          format: url
          example: 'https://www.acme-corp.com'
        phone:
          type: string
          example: 408-867-5309
      type: object
